// <auto-generated />
using System;
using KshatriyaSportsFoundations.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KshatriyaSportsFoundations.API.Migrations
{
    [DbContext(typeof(KshatriyaSportsFoundationsDbContext))]
    [Migration("20260227184328_EnquiriesTable-make Message field nullable")]
    partial class EnquiriesTablemakeMessagefieldnullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KshatriyaSportsFoundations.API.Models.Domain.EnquiryDomain", b =>
                {
                    b.Property<Guid>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("EnquiryId");

                    b.ToTable("Enquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
